version: '3.3'

services:
  app:
    container_name: nuveo_app
    build:
      context: ./app/docker/
    volumes:
      - ./app/src:/usr/src/app
    ports:
      - 5000:5000
    networks:
      - nuveo-app
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
  consumer:
    container_name: nuveo_customer_create_consumer
    build:
      context: ./consumer/docker/
    volumes:
      - ./consumer/src:/usr/src/app
      - ./consumer/customers_folder:/${NOVOS_CLIENTES}
    networks:
      - nuveo-app
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
  migration:
    container_name: nuveo_app_migration
    image: gosidekick/migration:v3.0.0
    command: exec -url "postgres://${PSQL_USER}:${PSQL_PWD}@db:5432/${PSQL_DB}?sslmode=disable" -dir ./fixtures -action up
    volumes:
      - ./app/fixtures:/fixtures
    networks:
      - nuveo-app
    depends_on:
      - db
  db:
    container_name: nuveo_db
    image: postgres:14.2
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data
    networks:
      - nuveo-app
    environment:
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PWD}

  rabbitmq:
    container_name: nuveo_rabbitmq
    image: rabbitmq:3-management-alpine
    volumes:
      - /var/lib/rabbitmq
    networks:
      - nuveo-app
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PWD}
    expose:
      - 5671
      - 5672
    ports:
      - 15671:15671
      - 15672:15672

networks:
  nuveo-app:
    driver: bridge